package ai.resourcepack.engine;

import ai.resourcepack.engine.api.BuildReport;
import ai.resourcepack.engine.api.BuiltPack;
import ai.resourcepack.engine.api.ContentRegistry;
import ai.resourcepack.engine.api.ContentSource;
import ai.resourcepack.engine.api.Diagnostic;
import ai.resourcepack.engine.api.LoadReport;
import ai.resourcepack.engine.api.ContentId;
import ai.resourcepack.engine.api.ItemInfo;
import ai.resourcepack.engine.api.Items;
import ai.resourcepack.engine.core.Host;
import ai.resourcepack.engine.core.bedrock.GeyserBridge;
import ai.resourcepack.engine.core.command.ContentCommands;
import ai.resourcepack.engine.core.command.EmoteCommands;
import ai.resourcepack.engine.core.command.EngineCommand;
import ai.resourcepack.engine.core.command.InterfaceCommands;
import ai.resourcepack.engine.core.command.LiquidCommands;
import ai.resourcepack.engine.core.command.ModelCommands;
import ai.resourcepack.engine.core.command.SyncCommands;
import ai.resourcepack.engine.core.distribution.BedrockSupport;
import ai.resourcepack.engine.core.distribution.DistributionManager;
import ai.resourcepack.engine.core.distribution.ProtocolResolver;
import ai.resourcepack.engine.core.entity.CustomEntities;
import ai.resourcepack.engine.core.entity.EntityDefinitions;
import ai.resourcepack.engine.core.liquid.LiquidDefinitions;
import ai.resourcepack.engine.core.liquid.LiquidPools;
import ai.resourcepack.engine.core.liquid.Liquids;
import ai.resourcepack.engine.core.emote.EmoteDirector;
import ai.resourcepack.engine.core.emote.EmoteStore;
import ai.resourcepack.engine.core.emote.EmoteInvites;
import ai.resourcepack.engine.core.emote.EmoteWording;
import ai.resourcepack.engine.core.emote.EmotesImpl;
import ai.resourcepack.engine.core.content.ContentFolderLoader;
import ai.resourcepack.engine.core.item.ItemAssets;
import ai.resourcepack.engine.core.item.ItemListener;
import ai.resourcepack.engine.core.item.ItemDefinitions;
import ai.resourcepack.engine.core.item.ItemsImpl;
import ai.resourcepack.engine.core.model.ModelDefinitions;
import ai.resourcepack.engine.core.model.ModelPlacementListener;
import ai.resourcepack.engine.core.model.RigAnimator;
import ai.resourcepack.engine.core.model.RigPlacementListener;
import ai.resourcepack.engine.core.model.ModelsImpl;
import ai.resourcepack.engine.core.model.RigStore;
import ai.resourcepack.engine.core.model.Seats;
import ai.resourcepack.engine.core.font.FontAssets;
import ai.resourcepack.engine.core.font.OverlayDefinitions;
import ai.resourcepack.engine.core.font.Overlays;
import ai.resourcepack.engine.core.font.IconDefinitions;
import ai.resourcepack.engine.core.font.IconsImpl;
import ai.resourcepack.engine.core.sound.SoundAssets;
import ai.resourcepack.engine.core.sound.SoundDefinitions;
import ai.resourcepack.engine.core.recipe.RecipeDefinitions;
import ai.resourcepack.engine.core.recipe.Recipes;
import ai.resourcepack.engine.core.sound.SoundsImpl;
import ai.resourcepack.engine.core.sync.StudioPush;
import ai.resourcepack.engine.core.sync.SyncClient;
import ai.resourcepack.engine.core.sync.SyncGroup;
import ai.resourcepack.engine.core.pack.PackBuilder;
import ai.resourcepack.engine.core.registry.ContentRegistryImpl;
import ai.resourcepack.engine.core.serve.BundleSessions;
import ai.resourcepack.engine.core.serve.PackDelivery;
import ai.resourcepack.engine.core.serve.PackHost;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;

/**
 * The plugin: loads the content folder, builds a pack per bundle, serves them,
 * and hands players the bundle they should be holding.
 *
 * <p>Thin on purpose. Everything it does is assembled from pieces that work
 * without a server, so this class is wiring and console output rather than
 * logic. If something here starts making decisions, that is the signal it
 * belongs one layer down where it can be tested.
 *
 * <p><strong>The plugin name is load-bearing and cannot change.</strong>
 * Persistent-data keys are namespaced by it, so a rename would orphan
 * everything placed in every world by every earlier version.
 */
public final class RPEnginePlugin extends JavaPlugin implements Listener {

    /** So the output folder can answer "is this mine?" without anybody asking. */
    private static final String OUTPUT_README = """
            Everything in this folder is generated by RP Engine.

            Your content goes in ../content/, one folder per pack. This folder holds
            the resource packs built from it, one zip per bundle. Editing a zip here
            does nothing: the next reload overwrites it.

            Safe to delete. It is rebuilt on the next start.
            """;

    private final ContentRegistryImpl registry = new ContentRegistryImpl();
    private final BundleSessions sessions = new BundleSessions();
    private ItemsImpl items;
    private ModelPlacementListener placements;
    private Recipes recipes;
    private SyncClient sync;
    private EmoteStore emoteStore;
    private EmoteDirector emotes;
    private EmoteInvites invites;
    private RigStore rigs;
    private RigAnimator animator;
    private RigPlacementListener rigPlacement;
    private ModelsImpl models;
    private Seats seats;
    private CustomEntities creatures;
    private LiquidPools pools;
    private Liquids liquids;
    private LiquidCommands liquidCommands;
    private ai.resourcepack.engine.core.skin.SkinApplier skins;
    private DistributionManager distribution;
    private BedrockSupport bedrock = BedrockSupport.NONE;

    /**
     * Players whose next quit is a Geyser transfer rather than a departure.
     *
     * <p>Serving a Bedrock pack reconnects them, which reaches the server as a
     * disconnect. Without this their sync pairing is dropped mid-apply.
     */
    private final java.util.Set<java.util.UUID> reconnecting =
            java.util.concurrent.ConcurrentHashMap.newKeySet();
    private final SyncGroup group = new SyncGroup();
    /** Recipes are outside the id space, so this is the only list of them. */
    private List<ContentId> recipeIds = List.of();
    private final SoundsImpl sounds = new SoundsImpl();
    private final IconsImpl icons = new IconsImpl();
    private final Overlays overlays = new Overlays();

    private PackHost host;
    private PackDelivery delivery;
    private List<BuiltPack> built = List.of();
    private String defaultBundle = "";

    @Override
    public void onEnable() {
        saveDefaultConfig();
        items = new ItemsImpl(this);
        // Emotes come over from the previous engine whole: the store, the
        // director and the maths. Host is the seam they were written against,
        // so it is what they get.
        // Animated rigs: studio's own placement path, beside ours. A studio
        // model is a carrier item dispatched by custom_model_data, so it is
        // identified and placed differently from a content-folder item — two
        // paths because there are genuinely two kinds of thing.
        // One Host for everything that borrows this plugin's scheduler,
        // listeners and key namespace. The rig side never asks for the emote
        // wording or the cast permission, but two Hosts differing only in the
        // fields one of them ignores is a thing to keep in step for no reason.
        Host host = new Host(this, getDataFolder(), new EmoteWording(),
                getConfig().getString("emotes.cast-permission", EmoteWording.MULTI_PERMISSION));
        skins = new ai.resourcepack.engine.core.skin.SkinApplier(this);

        // Geyser is a plugin a server may not have, and its classes are simply
        // not there when it does not. Probed once, and everything that asks
        // about Bedrock asks through the seam.
        if (getServer().getPluginManager().getPlugin("Geyser-Spigot") != null) {
            try {
                bedrock = new GeyserBridge(this, reconnecting::add);
                getLogger().info("Geyser found; Bedrock players are served their own pack.");
            } catch (RuntimeException | NoClassDefFoundError e) {
                getLogger().warning("Geyser is here but the bridge would not start: " + e.getMessage());
            }
        }
        distribution = new DistributionManager(this, bedrock, new ProtocolResolver(getLogger()),
                getConfig().getString("distribution.api-url", "https://studio.resourcepack.ai"));
        rigs = new RigStore(getDataFolder());
        rigs.load(getLogger());
        animator = new RigAnimator(host, rigs);
        rigPlacement = new RigPlacementListener(host, rigs, animator);
        models = new ModelsImpl(animator, rigs, rigPlacement);

        emoteStore = new EmoteStore(getDataFolder());
        emoteStore.load(getLogger());
        // EmoteWording rather than nothing. Three things an emote has to say
        // happen to somebody who did not run the command — being pulled in, an
        // emote ending, and finding on join that the one you were in did not
        // survive a crash — and EmoteMessages' own doc says silence there
        // reads as a bug.
        emotes = new EmoteDirector(host, emoteStore);
        seats = new Seats(this);
        creatures = new CustomEntities(this, items);
        pools = new LiquidPools(getDataFolder());
        pools.load(getLogger());
        liquids = new Liquids(this, pools);
        placements = new ModelPlacementListener(this, items, seats);
        recipes = new Recipes(this, items);
        getServer().getPluginManager().registerEvents(this, this);
        getServer().getPluginManager().registerEvents(placements, this);
        getServer().getPluginManager().registerEvents(seats, this);
        getServer().getPluginManager().registerEvents(creatures, this);
        liquids.start();
        getServer().getPluginManager().registerEvents(new ItemListener(items), this);
        sync = new SyncClient(
                getConfig().getString("sync.url", "wss://sync.resourcepack.ai/connect"),
                getConfig().getString("sync.server-token", ""),
                getLogger(), this::onStudioPush, this::onStudioGive,
                this::onStudioSkin, this::onStudioTell);
        invites = new EmoteInvites(this, emotes());
        // The handle an event carries, wired both ways at startup exactly as
        // the library does it.
        animator.placements(models::handleFor);
        rigPlacement.placements(models::handleFor);
        getServer().getPluginManager().registerEvents(rigPlacement, this);
        animator.start();

        getServer().getPluginManager().registerEvents(emotes, this);
        emotes.start();
        getServer().getPluginManager().registerEvents(distribution, this);
        distribution.start();
        // A trusted server holds the socket open from startup: it announces
        // who is online rather than waiting for somebody to type a code, and
        // an announcement down a socket that is not there is nothing at all.
        if (sync.announcesPresence() && !sync.open()) {
            getLogger().warning("Could not reach studio, so this server is not announcing presence.");
        }

        startHost();
        registerCommands();
        rebuild(getServer().getConsoleSender());
    }

    /**
     * Hands every command to {@link EngineCommand}.
     *
     * <p>After {@link #startHost()}, because two of the areas need the host
     * and the delivery it makes. The areas take the services they use and
     * nothing else; what they cannot be given is this plugin's own lifecycle,
     * which arrives as the four callbacks below.
     */
    private void registerCommands() {
        liquidCommands = new LiquidCommands(liquids, pools, getLogger());
        EngineCommand commands = new EngineCommand(registry, () -> built,
                new ContentCommands(items, () -> built, host, recipes, () -> recipeIds,
                        this::reloadContent, this::sendPack),
                new ModelCommands(placements, creatures),
                new InterfaceCommands(sounds, icons, overlays),
                new EmoteCommands(emotes, invites),
                new SyncCommands(getServer(), sync, group, distribution,
                        this::announceMembers, this::unpush),
                liquidCommands);

        for (String name : List.of("rpengine", "emote", "emotereply")) {
            org.bukkit.command.PluginCommand registered = getCommand(name);
            if (registered == null) {
                // plugin.yml and this list disagreeing is a packaging mistake,
                // and a silent one: the command simply does nothing in game.
                getLogger().warning("plugin.yml declares no /" + name + ".");
                continue;
            }
            registered.setExecutor(commands);
            registered.setTabCompleter(commands);
        }
    }

    /**
     * {@code /rp reload}: config.yml as well as the content.
     *
     * <p>Reloading the content but not the settings is the sort of half-reload
     * that has somebody restarting the server anyway and wondering why the
     * command exists.
     */
    private void reloadContent(CommandSender to) {
        reloadConfig();
        defaultBundle = getConfig().getString("default-bundle", "");
        rebuild(to);
    }

    /** {@code /rp push}: forget what they are holding and send it again. */
    private void sendPack(Player player) {
        sessions.forget(player.getUniqueId());
        player.sendMessage("[RPEngine] "
                + (delivery.apply(player, desiredFor(player)) ? "Sent." : "Nothing to send."));
    }

    /** The studio models this server holds, and the rigs standing in its worlds. */
    public ai.resourcepack.engine.api.Models models() {
        return models;
    }

    /** The emotes this server holds. */
    public ai.resourcepack.engine.api.Emotes emotes() {
        return new EmotesImpl(emotes, emoteStore);
    }

    @Override
    public void onDisable() {
        if (invites != null) {
            // An invitation nobody can answer is worse than none: the task
            // that would have expired it goes with the plugin.
            invites.clear();
        }
        if (emotes != null) {
            // Everybody mid-emote is put back before the plugin goes, or they
            // stay invisible with a rig standing where they were.
            emotes.stop();
        }
        if (emoteStore != null) {
            emoteStore.save(getLogger());
        }
        if (liquids != null) {
            liquids.stop();
        }
        if (pools != null) {
            pools.save(getLogger());
        }
        if (seats != null) {
            // Everybody gets up before the plugin goes. A marker stand is not
            // persistent, so one left behind would survive until its chunk
            // unloaded — long enough to be a bug report.
            seats.clear();
        }
        if (distribution != null) {
            distribution.shutdown();
        }
        if (bedrock instanceof GeyserBridge) {
            // Unsubscribes from Geyser's event bus. Without it a reload leaves
            // a dead listener wired to a live bus.
            ((GeyserBridge) bedrock).shutdown();
        }
        if (animator != null) {
            animator.stop();
        }
        if (rigs != null) {
            rigs.save(getLogger());
        }
        // Recipes live in the server's registry rather than ours, so leaving
        // them behind would outlast the plugin that made them.
        if (recipes != null) {
            recipes.clear();
        }
        if (sync != null) {
            sync.close();
        }
        if (host != null) {
            host.stop();
        }
    }

    /** What this server holds. The supported way in for another plugin. */
    public ContentRegistry registry() {
        return registry;
    }

    /**
     * The way a third-party plugin puts content of its own into this server.
     *
     * <p>Separate from {@link #registry()} because reading what a server holds
     * and adding to it are different privileges, and the great majority of
     * callers only want the first. Claim a namespace, define into the handle,
     * and release it when your plugin disables — see {@link ai.resourcepack.engine.api.Namespace}.
     */
    public ai.resourcepack.engine.api.ContentRegistration registration() {
        return registry;
    }

    /** The icons this server holds, and the way to put one into text. */
    public ai.resourcepack.engine.api.Icons icons() {
        return icons;
    }

    /** The custom sounds this server holds. */
    public ai.resourcepack.engine.api.Sounds sounds() {
        return sounds;
    }

    /** The custom items this server holds. */
    public Items items() {
        return items;
    }

    private void startHost() {
        defaultBundle = getConfig().getString("default-bundle", "");
        String address = getConfig().getString("host.public-address", "http://127.0.0.1:8181");
        host = new PackHost(address);
        delivery = new PackDelivery(sessions, host,
                getConfig().getString("prompt.message", ""),
                getConfig().getBoolean("prompt.force", false));

        if (!getConfig().getBoolean("host.enabled", true)) {
            getLogger().info("Pack hosting is off. Packs are built but not served.");
            return;
        }
        try {
            int port = host.start(getConfig().getInt("host.port", 8181));
            getLogger().info("Serving packs on port " + port + " as " + address);
        } catch (IOException e) {
            getLogger().warning("Could not listen on port " + getConfig().getInt("host.port", 8181)
                    + ": " + e.getMessage() + ". Packs are built but not served.");
        }
    }

    /**
     * Reads the content folder, builds every bundle, and re-serves them.
     *
     * <p>Everything is rebuilt rather than diffed. A namespace is replaced
     * whole or not at all, and the same reasoning applies here: a partial
     * rebuild is how the registry ends up disagreeing with the zip somebody is
     * holding.
     */
    private void rebuild(CommandSender to) {
        // content/ is yours and output/ is ours. The names are doing real work
        // here: a folder called packs/ reads as "put your packs in me", which is
        // the one mistake a new user is most likely to make on day one.
        Path content = getDataFolder().toPath().resolve("content");
        Path output = getDataFolder().toPath().resolve("output");
        try {
            Files.createDirectories(content);
            Files.createDirectories(output);
            Files.writeString(output.resolve("README.txt"), OUTPUT_README);
        } catch (IOException e) {
            to.sendMessage("[RPEngine] Could not prepare " + getDataFolder() + ": " + e.getMessage());
            return;
        }

        // Everything goes, then the folder is read again. See clear().
        registry.clear();

        LoadReport loaded = new ContentFolderLoader(registry).load(content, ContentSource.AUTHORED);
        report(to, "content", loaded.diagnostics());

        ItemDefinitions.Result parsedItems = ItemDefinitions.parse(loaded);
        report(to, "items", parsedItems.diagnostics());
        // Needs a running server, so it lives out here rather than in parse().
        report(to, "items", ItemDefinitions.checkGivable(parsedItems));
        items.replace(parsedItems.items());

        ModelDefinitions.Result parsedModels =
                ModelDefinitions.parse(loaded, parsedItems.items(), measure(content, parsedItems));
        report(to, "model", parsedModels.diagnostics());
        placements.replace(parsedModels.model());

        EntityDefinitions.Result parsedEntities = EntityDefinitions.parse(loaded);
        report(to, "entities", parsedEntities.diagnostics());
        creatures.replace(parsedEntities.entities());

        LiquidDefinitions.Result parsedLiquids = LiquidDefinitions.parse(loaded);
        report(to, "liquids", parsedLiquids.diagnostics());
        liquids.replace(parsedLiquids.liquids());

        SoundDefinitions.Result parsedSounds = SoundDefinitions.parse(loaded);
        report(to, "sounds", parsedSounds.diagnostics());
        sounds.replace(parsedSounds.sounds());

        IconDefinitions.Result parsedIcons = IconDefinitions.parse(loaded);
        report(to, "icons", parsedIcons.diagnostics());
        icons.replace(parsedIcons.icons());

        OverlayDefinitions.Result parsedScreens = OverlayDefinitions.screens(loaded);
        OverlayDefinitions.Result parsedHuds = OverlayDefinitions.huds(loaded);
        report(to, "screens", parsedScreens.diagnostics());
        report(to, "huds", parsedHuds.diagnostics());
        overlays.replace(parsedScreens.overlays(), parsedHuds.overlays());

        BuildReport builtReport = new PackBuilder(
                getConfig().getInt("pack.format", PackBuilder.PACK_FORMAT),
                getConfig().getString("pack.description", "RP Engine"))
                .with(new ItemAssets())
                .with(new SoundAssets())
                .with(new FontAssets())
                .build(content, output, loaded);
        report(to, "build", builtReport.diagnostics());

        // After the items exist, because a recipe's ingredients and result are
        // resolved against them.
        RecipeDefinitions.Result parsedRecipes = RecipeDefinitions.parse(loaded);
        report(to, "recipes", parsedRecipes.diagnostics());
        recipeIds = List.copyOf(parsedRecipes.recipes().keySet());
        for (String problem : recipes.replace(parsedRecipes.recipes())) {
            getLogger().warning("recipe " + problem);
        }

        built = builtReport.packs();
        for (BuiltPack pack : built) {
            host.register(pack);
        }

        to.sendMessage("[RPEngine] " + plural(loaded.packs().size(), "pack") + ", "
                + plural(loaded.definitions().size(), "definition") + ", "
                + plural(built.size(), "bundle") + " built, "
                + plural(recipes.size(), "recipe") + ".");

        // Everybody online is holding a pack that may no longer exist, so they
        // are re-sent before they notice. Nothing is sent to a player whose
        // stack is already right.
        for (Player player : getServer().getOnlinePlayers()) {
            delivery.apply(player, desiredFor(player));
        }
    }

    /**
     * Measures every item that has a model, so placed model can default its
     * hitbox to what you can actually see.
     *
     * <p>Reads the geometry a second time, which the builder also does. Worth
     * it: threading measurements out of the build would put the pack builder
     * in the business of telling the placed model layer things, and these files
     * are small and read once per reload.
     */
    private java.util.Map<ai.resourcepack.engine.api.ContentId, ai.resourcepack.engine.core.item.Geometry.Bounds>
            measure(Path content, ItemDefinitions.Result parsed) {
        java.util.Map<ai.resourcepack.engine.api.ContentId,
                ai.resourcepack.engine.core.item.Geometry.Bounds> measured = new java.util.HashMap<>();
        for (ItemInfo item : parsed.items().values()) {
            String name = item.model().orElse(null);
            if (name == null) {
                continue;
            }
            Path file = content.resolve(item.id().namespace())
                    .resolve("assets").resolve("models").resolve(name + ".json");
            if (!Files.isRegularFile(file)) {
                continue;
            }
            try {
                ai.resourcepack.engine.core.item.Geometry
                        .read(Files.readAllBytes(file), item.id().namespace())
                        .ifPresent(model -> measured.put(item.id(), model.bounds()));
            } catch (IOException e) {
                // The builder reports this properly. Failing to measure just
                // means the hitbox falls back to one block.
                getLogger().fine("Could not measure " + item.id() + ": " + e.getMessage());
            }
        }
        return measured;
    }

    /**
     * A pack studio pushed: fetch it, serve it, put it on whoever claimed the
     * code.
     *
     * <p>Arrives on the websocket thread, so everything that touches a player
     * hops back to the main thread. The download deliberately does not: a
     * pack is megabytes and blocking the server on it would be a lag spike
     * every time somebody clicks push in the panel.
     */
    private void onStudioPush(String code, String payload) {
        String claimant = sync.claimant(code);
        if (claimant == null) {
            sync.failed(code, "unknown-code");
            return;
        }
        // The manifest first: a pack whose art arrives without its keyframes
        // is a pack somebody can wear and not emote in, and the two came down
        // the same push.
        // The rigs manifest is what makes a placed studio model animate. Same
        // push, different slot; see StudioPush.
        StudioPush.rigsUrl(payload)
                .flatMap(StudioPush::fetchText)
                .ifPresent(json -> {
                    ai.resourcepack.engine.api.MergeResult merged = rigs.updateFromJson(json);
                    if (merged.ok()) {
                        rigs.save(getLogger());
                        getLogger().info("Rigs: " + merged.count() + " from " + merged.packId() + ".");
                    } else {
                        getLogger().warning("Rig manifest: " + merged.error());
                    }
                });

        StudioPush.emotesUrl(payload)
                .flatMap(StudioPush::fetchText)
                .ifPresent(json -> {
                    ai.resourcepack.engine.api.MergeResult merged = emoteStore.updateFromJson(json);
                    if (merged.ok()) {
                        emoteStore.save(getLogger());
                        getLogger().info("Emotes: " + merged.count() + " from " + merged.packId() + ".");
                    } else {
                        getLogger().warning("Emote manifest: " + merged.error());
                    }
                });

        Optional<BuiltPack> pack = StudioPush.fetch(payload,
                getDataFolder().toPath().resolve("output"));
        if (pack.isEmpty()) {
            sync.failed(code, StudioPush.reason);
            return;
        }
        getServer().getScheduler().runTask(this, () -> {
            host.register(pack.get());
            int reached = 0;
            for (String name : group.recipients(code)) {
                Player player = getServer().getPlayerExact(name);
                if (player == null) {
                    continue;
                }
                pushTo(player, pack.get());
                player.sendMessage("[RPEngine] Studio pushed a pack.");
                reached++;
            }
            if (reached == 0) {
                sync.failed(code, "player-offline");
                return;
            }
            sync.applied(code);
        });
    }

    /**
     * Puts a pushed pack on one player.
     *
     * <p>Stacked ON TOP of whatever the server's own content gave THEM — their
     * bundle, not the claimer's, since somebody sharing a sync may be in a
     * different world with different content — so a pack under test is tried
     * against the server it will actually run on.
     */
    private void pushTo(Player player, BuiltPack pack) {
        List<BuiltPack> stack = new ArrayList<>(desiredFor(player));
        stack.removeIf(held -> held.bundle().equals(StudioPush.BUNDLE));
        stack.add(pack);
        delivery.apply(player, stack);
    }

    /** Takes a pushed pack back off somebody, leaving the server's own content. */
    private void unpush(String name) {
        Player player = getServer().getPlayerExact(name);
        if (player != null) {
            delivery.apply(player, desiredFor(player));
        }
    }

    /** Tells studio the roster, which it wants whole on every change. */
    private void announceMembers(String code) {
        List<String> entries = new ArrayList<>();
        for (String name : group.recipients(code)) {
            Player player = getServer().getPlayerExact(name);
            if (player != null) {
                entries.add(player.getUniqueId().toString().replace("-", "")
                        + ":" + player.getName() + ":java");
            }
        }
        sync.members(code, entries);
    }

    /**
     * A signed skin studio pushed: the player wears it.
     *
     * <p>The value and signature are Mojang's own, fetched and signed by
     * studio. Nothing here validates them beyond their shape — the game does
     * that when the profile is applied, and a second opinion invented here
     * would be a guess about somebody else's cryptography.
     */
    private void onStudioSkin(String code, String payload) {
        String[] texture = payload.split(" ", 2);
        if (texture.length < 2 || texture[0].isEmpty() || texture[1].isEmpty()) {
            sync.skinFailed(code, "bad-payload");
            return;
        }
        getServer().getScheduler().runTask(this, () -> {
            int worn = 0;
            for (String name : group.recipients(code)) {
                Player player = getServer().getPlayerExact(name);
                if (player == null) {
                    continue;
                }
                if (skins.apply(player, texture[0], texture[1]).ok) {
                    worn++;
                }
            }
            if (worn == 0) {
                sync.skinFailed(code, "player-offline");
                return;
            }
            sync.skinned(code);
        });
    }

    /**
     * A line of chat studio asked for — usually that a model somebody walked
     * away from has finished.
     *
     * <p>The payload is JSON because a notification is prose and its fields
     * contain spaces. The shape is the plugin's to own, which is why the
     * wording below is here and not in the protocol.
     */
    private void onStudioTell(String code, String json) {
        String title = jsonString(json, "title");
        if (title == null) {
            sync.tellFailed(code, "bad-payload");
            return;
        }
        String body = jsonString(json, "body");
        String url = jsonString(json, "url");
        getServer().getScheduler().runTask(this, () -> {
            int told = 0;
            for (String name : group.recipients(code)) {
                Player player = getServer().getPlayerExact(name);
                if (player == null) {
                    continue;
                }
                player.sendMessage("[RPEngine] " + title);
                if (body != null && !body.isEmpty()) {
                    player.sendMessage("[RPEngine] " + body);
                }
                if (url != null && !url.isEmpty()) {
                    player.sendMessage("[RPEngine] " + url);
                }
                told++;
            }
            if (told == 0) {
                sync.tellFailed(code, "player-offline");
                return;
            }
            sync.told(code);
        });
    }

    /**
     * One string field out of a small, known JSON object.
     *
     * <p>Gson would do this properly and is already on the classpath, but the
     * payload is three fields written by us and read by us, and a parse that
     * throws on a field somebody adds later is worse here than one that simply
     * does not find it.
     */
    private static String jsonString(String json, String field) {
        try {
            com.google.gson.JsonElement parsed = com.google.gson.JsonParser.parseString(json);
            if (!parsed.isJsonObject()) {
                return null;
            }
            com.google.gson.JsonElement value = parsed.getAsJsonObject().get(field);
            return value != null && value.isJsonPrimitive() ? value.getAsString() : null;
        } catch (RuntimeException e) {
            return null;
        }
    }

    /** A give-command studio asked for, run as the console against that player. */
    private void onStudioGive(String code, String command) {
        String claimant = sync.claimant(code);
        if (claimant == null) {
            sync.giveFailed(code, "unknown-code");
            return;
        }
        getServer().getScheduler().runTask(this, () -> {
            Player player = getServer().getPlayerExact(claimant);
            if (player == null) {
                sync.giveFailed(code, "player-offline");
                return;
            }
            try {
                // @p in the command resolves against the player's own position
                // rather than the console's, which is nowhere.
                String resolved = command.startsWith("/") ? command.substring(1) : command;
                getServer().dispatchCommand(getServer().getConsoleSender(),
                        "execute at " + player.getName() + " run " + resolved);
                sync.given(code);
            } catch (RuntimeException e) {
                getLogger().warning("Studio give failed: " + e.getMessage());
                sync.giveFailed(code, "exception");
            }
        });
    }

    private void report(CommandSender to, String stage, List<Diagnostic> diagnostics) {
        for (Diagnostic diagnostic : diagnostics) {
            // The logger adds its own [RPEngine], so this one does not.
            String line = diagnostic.severity().name().toLowerCase(Locale.ROOT)
                    + " in " + stage + ": " + diagnostic;
            if (diagnostic.severity() == Diagnostic.Severity.ERROR) {
                getLogger().warning(line);
            } else {
                getLogger().info(line);
            }
            if (!(to instanceof org.bukkit.command.ConsoleCommandSender)) {
                to.sendMessage("[RPEngine] " + line);
            }
        }
    }

    /** "1 item", "2 items". Cheap, and its absence is the sort of thing that reads as unfinished. */
    private static String plural(int count, String noun) {
        return count + " " + noun + (count == 1 ? "" : "s");
    }

    /**
     * Which bundles a player should be holding.
     *
     * <p>One bundle, from the config, and that is the whole policy for now.
     * Per-world and per-permission selection is a server's decision rather
     * than ours, so it arrives as an API rather than as a guess.
     */
    private List<BuiltPack> desiredFor(Player player) {
        if (defaultBundle.isEmpty()) {
            return List.of();
        }
        for (BuiltPack pack : built) {
            if (pack.bundle().equals(defaultBundle)) {
                return List.of(pack);
            }
        }
        return List.of();
    }

    /**
     * Tells studio who is here, on a server that holds the trusted token.
     *
     * <p>What it buys: a push addressed to a player by uuid, with nobody
     * typing a code. A server without the token announces nothing and pairs
     * the ordinary way.
     */
    private void announcePresence(Player player, boolean here) {
        if (sync == null || !sync.announcesPresence()) {
            return;
        }
        if (here) {
            sync.present(player.getUniqueId(), player.getName(),
                    bedrock.isBedrock(player.getUniqueId()));
        } else {
            sync.gone(player.getUniqueId());
        }
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent event) {
        announcePresence(event.getPlayer(), true);
        delivery.apply(event.getPlayer(), desiredFor(event.getPlayer()));
    }

    @EventHandler
    public void onQuit(PlayerQuitEvent event) {
        if (reconnecting.remove(event.getPlayer().getUniqueId())) {
            // A Geyser transfer, not a departure. Everything below would undo
            // an apply that is still in flight.
            return;
        }
        announcePresence(event.getPlayer(), false);
        overlays.clear(event.getPlayer());
        if (liquidCommands != null) {
            liquidCommands.forget(event.getPlayer().getUniqueId());
        }
        // A client drops its packs on disconnect, so believing otherwise would
        // mean sending nothing to somebody who has nothing.
        sessions.forget(event.getPlayer().getUniqueId());
        // Studio stops offering to push to somebody who is not here.
        if (sync != null) {
            // If they owned a sync it ends and everybody on it loses the pack,
            // because nobody inherits one. That is the whole reason this is a
            // sync rather than a party.
            for (String name : group.forget(event.getPlayer().getName())) {
                unpush(name);
            }
            sync.forget(event.getPlayer().getName());
        }
    }

}
