package ai.resourcepack.engine;

import ai.resourcepack.engine.api.BuildReport;
import ai.resourcepack.engine.api.BuiltPack;
import ai.resourcepack.engine.api.ContentKind;
import ai.resourcepack.engine.api.ContentRegistry;
import ai.resourcepack.engine.api.ContentSource;
import ai.resourcepack.engine.api.Diagnostic;
import ai.resourcepack.engine.api.LoadReport;
import ai.resourcepack.engine.api.ContentId;
import ai.resourcepack.engine.api.ItemInfo;
import ai.resourcepack.engine.api.Items;
import ai.resourcepack.engine.core.Host;
import ai.resourcepack.engine.core.command.Completions;
import ai.resourcepack.engine.core.emote.EmoteDirector;
import ai.resourcepack.engine.core.emote.EmoteStore;
import ai.resourcepack.engine.core.emote.EmotesImpl;
import ai.resourcepack.engine.core.content.ContentFolderLoader;
import ai.resourcepack.engine.core.item.ItemAssets;
import ai.resourcepack.engine.core.item.ItemListener;
import ai.resourcepack.engine.core.item.ItemDefinitions;
import ai.resourcepack.engine.core.item.ItemsImpl;
import ai.resourcepack.engine.core.model.ModelDefinitions;
import ai.resourcepack.engine.core.model.ModelPlacementListener;
import ai.resourcepack.engine.core.font.FontAssets;
import ai.resourcepack.engine.core.font.OverlayDefinitions;
import ai.resourcepack.engine.core.font.Overlays;
import ai.resourcepack.engine.core.font.IconDefinitions;
import ai.resourcepack.engine.core.font.IconsImpl;
import ai.resourcepack.engine.core.sound.SoundAssets;
import ai.resourcepack.engine.core.sound.SoundDefinitions;
import ai.resourcepack.engine.core.recipe.RecipeDefinitions;
import ai.resourcepack.engine.core.recipe.Recipes;
import ai.resourcepack.engine.core.sound.SoundsImpl;
import ai.resourcepack.engine.core.sync.StudioPush;
import ai.resourcepack.engine.core.sync.SyncClient;
import ai.resourcepack.engine.core.sync.SyncGroup;
import ai.resourcepack.engine.core.pack.PackBuilder;
import ai.resourcepack.engine.core.registry.ContentRegistryImpl;
import ai.resourcepack.engine.core.serve.BundleSessions;
import ai.resourcepack.engine.core.serve.PackDelivery;
import ai.resourcepack.engine.core.serve.PackHost;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;

/**
 * The plugin: loads the content folder, builds a pack per bundle, serves them,
 * and hands players the bundle they should be holding.
 *
 * <p>Thin on purpose. Everything it does is assembled from pieces that work
 * without a server, so this class is wiring and console output rather than
 * logic. If something here starts making decisions, that is the signal it
 * belongs one layer down where it can be tested.
 *
 * <p><strong>The plugin name is load-bearing and cannot change.</strong>
 * Persistent-data keys are namespaced by it, so a rename would orphan
 * everything placed in every world by every earlier version.
 */
public final class RPEnginePlugin extends JavaPlugin implements Listener {

    /** So the output folder can answer "is this mine?" without anybody asking. */
    private static final String OUTPUT_README = """
            Everything in this folder is generated by RP Engine.

            Your content goes in ../content/, one folder per pack. This folder holds
            the resource packs built from it, one zip per bundle. Editing a zip here
            does nothing: the next reload overwrites it.

            Safe to delete. It is rebuilt on the next start.
            """;

    private final ContentRegistryImpl registry = new ContentRegistryImpl();
    private final BundleSessions sessions = new BundleSessions();
    private ItemsImpl items;
    private ModelPlacementListener placements;
    private Recipes recipes;
    private SyncClient sync;
    private EmoteStore emoteStore;
    private EmoteDirector emotes;
    private final SyncGroup group = new SyncGroup();
    /** Recipes are outside the id space, so this is the only list of them. */
    private List<ContentId> recipeIds = List.of();
    private final SoundsImpl sounds = new SoundsImpl();
    private final IconsImpl icons = new IconsImpl();
    private final Overlays overlays = new Overlays();

    private PackHost host;
    private PackDelivery delivery;
    private List<BuiltPack> built = List.of();
    private String defaultBundle = "";

    @Override
    public void onEnable() {
        saveDefaultConfig();
        items = new ItemsImpl(this);
        // Emotes come over from the previous engine whole: the store, the
        // director and the maths. Host is the seam they were written against,
        // so it is what they get.
        emoteStore = new EmoteStore(getDataFolder());
        emoteStore.load(getLogger());
        emotes = new EmoteDirector(
                new Host(this, getDataFolder(), null, getConfig().getString("emotes.cast-permission", null)),
                emoteStore);
        placements = new ModelPlacementListener(this, items);
        recipes = new Recipes(this, items);
        getServer().getPluginManager().registerEvents(this, this);
        getServer().getPluginManager().registerEvents(placements, this);
        getServer().getPluginManager().registerEvents(new ItemListener(items), this);
        sync = new SyncClient(
                getConfig().getString("sync.url", "wss://sync.resourcepack.ai/connect"),
                getLogger(), this::onStudioPush, this::onStudioGive);
        getServer().getPluginManager().registerEvents(emotes, this);
        emotes.start();
        startHost();
        rebuild(getServer().getConsoleSender());
    }

    /** The emotes this server holds. */
    public ai.resourcepack.engine.api.Emotes emotes() {
        return new EmotesImpl(emotes, emoteStore);
    }

    @Override
    public void onDisable() {
        if (emotes != null) {
            // Everybody mid-emote is put back before the plugin goes, or they
            // stay invisible with a rig standing where they were.
            emotes.stop();
        }
        if (emoteStore != null) {
            emoteStore.save(getLogger());
        }
        // Recipes live in the server's registry rather than ours, so leaving
        // them behind would outlast the plugin that made them.
        if (recipes != null) {
            recipes.clear();
        }
        if (sync != null) {
            sync.close();
        }
        if (host != null) {
            host.stop();
        }
    }

    /** What this server holds. The supported way in for another plugin. */
    public ContentRegistry registry() {
        return registry;
    }

    /** The icons this server holds, and the way to put one into text. */
    public ai.resourcepack.engine.api.Icons icons() {
        return icons;
    }

    /** The custom sounds this server holds. */
    public ai.resourcepack.engine.api.Sounds sounds() {
        return sounds;
    }

    /** The custom items this server holds. */
    public Items items() {
        return items;
    }

    private void startHost() {
        defaultBundle = getConfig().getString("default-bundle", "");
        String address = getConfig().getString("host.public-address", "http://127.0.0.1:8181");
        host = new PackHost(address);
        delivery = new PackDelivery(sessions, host,
                getConfig().getString("prompt.message", ""),
                getConfig().getBoolean("prompt.force", false));

        if (!getConfig().getBoolean("host.enabled", true)) {
            getLogger().info("Pack hosting is off. Packs are built but not served.");
            return;
        }
        try {
            int port = host.start(getConfig().getInt("host.port", 8181));
            getLogger().info("Serving packs on port " + port + " as " + address);
        } catch (IOException e) {
            getLogger().warning("Could not listen on port " + getConfig().getInt("host.port", 8181)
                    + ": " + e.getMessage() + ". Packs are built but not served.");
        }
    }

    /**
     * Reads the content folder, builds every bundle, and re-serves them.
     *
     * <p>Everything is rebuilt rather than diffed. A namespace is replaced
     * whole or not at all, and the same reasoning applies here: a partial
     * rebuild is how the registry ends up disagreeing with the zip somebody is
     * holding.
     */
    private void rebuild(CommandSender to) {
        // content/ is yours and output/ is ours. The names are doing real work
        // here: a folder called packs/ reads as "put your packs in me", which is
        // the one mistake a new user is most likely to make on day one.
        Path content = getDataFolder().toPath().resolve("content");
        Path output = getDataFolder().toPath().resolve("output");
        try {
            Files.createDirectories(content);
            Files.createDirectories(output);
            Files.writeString(output.resolve("README.txt"), OUTPUT_README);
        } catch (IOException e) {
            to.sendMessage("[RPEngine] Could not prepare " + getDataFolder() + ": " + e.getMessage());
            return;
        }

        // Everything goes, then the folder is read again. See clear().
        registry.clear();

        LoadReport loaded = new ContentFolderLoader(registry).load(content, ContentSource.AUTHORED);
        report(to, "content", loaded.diagnostics());

        ItemDefinitions.Result parsedItems = ItemDefinitions.parse(loaded);
        report(to, "items", parsedItems.diagnostics());
        // Needs a running server, so it lives out here rather than in parse().
        report(to, "items", ItemDefinitions.checkGivable(parsedItems));
        items.replace(parsedItems.items());

        ModelDefinitions.Result parsedModels =
                ModelDefinitions.parse(loaded, parsedItems.items(), measure(content, parsedItems));
        report(to, "model", parsedModels.diagnostics());
        placements.replace(parsedModels.model());

        SoundDefinitions.Result parsedSounds = SoundDefinitions.parse(loaded);
        report(to, "sounds", parsedSounds.diagnostics());
        sounds.replace(parsedSounds.sounds());

        IconDefinitions.Result parsedIcons = IconDefinitions.parse(loaded);
        report(to, "icons", parsedIcons.diagnostics());
        icons.replace(parsedIcons.icons());

        OverlayDefinitions.Result parsedScreens = OverlayDefinitions.screens(loaded);
        OverlayDefinitions.Result parsedHuds = OverlayDefinitions.huds(loaded);
        report(to, "screens", parsedScreens.diagnostics());
        report(to, "huds", parsedHuds.diagnostics());
        overlays.replace(parsedScreens.overlays(), parsedHuds.overlays());

        BuildReport builtReport = new PackBuilder(
                getConfig().getInt("pack.format", PackBuilder.PACK_FORMAT),
                getConfig().getString("pack.description", "RP Engine"))
                .with(new ItemAssets())
                .with(new SoundAssets())
                .with(new FontAssets())
                .build(content, output, loaded);
        report(to, "build", builtReport.diagnostics());

        // After the items exist, because a recipe's ingredients and result are
        // resolved against them.
        RecipeDefinitions.Result parsedRecipes = RecipeDefinitions.parse(loaded);
        report(to, "recipes", parsedRecipes.diagnostics());
        recipeIds = List.copyOf(parsedRecipes.recipes().keySet());
        for (String problem : recipes.replace(parsedRecipes.recipes())) {
            getLogger().warning("recipe " + problem);
        }

        built = builtReport.packs();
        for (BuiltPack pack : built) {
            host.register(pack);
        }

        to.sendMessage("[RPEngine] " + plural(loaded.packs().size(), "pack") + ", "
                + plural(loaded.definitions().size(), "definition") + ", "
                + plural(built.size(), "bundle") + " built, "
                + plural(recipes.size(), "recipe") + ".");

        // Everybody online is holding a pack that may no longer exist, so they
        // are re-sent before they notice. Nothing is sent to a player whose
        // stack is already right.
        for (Player player : getServer().getOnlinePlayers()) {
            delivery.apply(player, desiredFor(player));
        }
    }

    /**
     * Measures every item that has a model, so placed model can default its
     * hitbox to what you can actually see.
     *
     * <p>Reads the geometry a second time, which the builder also does. Worth
     * it: threading measurements out of the build would put the pack builder
     * in the business of telling the placed model layer things, and these files
     * are small and read once per reload.
     */
    private java.util.Map<ai.resourcepack.engine.api.ContentId, ai.resourcepack.engine.core.item.Geometry.Bounds>
            measure(Path content, ItemDefinitions.Result parsed) {
        java.util.Map<ai.resourcepack.engine.api.ContentId,
                ai.resourcepack.engine.core.item.Geometry.Bounds> measured = new java.util.HashMap<>();
        for (ai.resourcepack.engine.api.ItemInfo item : parsed.items().values()) {
            String name = item.model().orElse(null);
            if (name == null) {
                continue;
            }
            Path file = content.resolve(item.id().namespace())
                    .resolve("assets").resolve("models").resolve(name + ".json");
            if (!Files.isRegularFile(file)) {
                continue;
            }
            try {
                ai.resourcepack.engine.core.item.Geometry
                        .read(Files.readAllBytes(file), item.id().namespace())
                        .ifPresent(model -> measured.put(item.id(), model.bounds()));
            } catch (IOException e) {
                // The builder reports this properly. Failing to measure just
                // means the hitbox falls back to one block.
                getLogger().fine("Could not measure " + item.id() + ": " + e.getMessage());
            }
        }
        return measured;
    }

    /**
     * A pack studio pushed: fetch it, serve it, put it on whoever claimed the
     * code.
     *
     * <p>Arrives on the websocket thread, so everything that touches a player
     * hops back to the main thread. The download deliberately does not: a
     * pack is megabytes and blocking the server on it would be a lag spike
     * every time somebody clicks push in the panel.
     */
    private void onStudioPush(String code, String payload) {
        String claimant = sync.claimant(code);
        if (claimant == null) {
            sync.failed(code, "unknown-code");
            return;
        }
        // The manifest first: a pack whose art arrives without its keyframes
        // is a pack somebody can wear and not emote in, and the two came down
        // the same push.
        StudioPush.emotesUrl(payload)
                .flatMap(StudioPush::fetchText)
                .ifPresent(json -> {
                    ai.resourcepack.engine.api.MergeResult merged = emoteStore.updateFromJson(json);
                    if (merged.ok()) {
                        emoteStore.save(getLogger());
                        getLogger().info("Emotes: " + merged.count() + " from " + merged.packId() + ".");
                    } else {
                        getLogger().warning("Emote manifest: " + merged.error());
                    }
                });

        Optional<BuiltPack> pack = StudioPush.fetch(payload,
                getDataFolder().toPath().resolve("output"));
        if (pack.isEmpty()) {
            sync.failed(code, StudioPush.reason);
            return;
        }
        getServer().getScheduler().runTask(this, () -> {
            host.register(pack.get());
            int reached = 0;
            for (String name : group.recipients(code)) {
                Player player = getServer().getPlayerExact(name);
                if (player == null) {
                    continue;
                }
                pushTo(player, pack.get());
                player.sendMessage("[RPEngine] Studio pushed a pack.");
                reached++;
            }
            if (reached == 0) {
                sync.failed(code, "player-offline");
                return;
            }
            sync.applied(code);
        });
    }

    /**
     * The whole of {@code /rp sync}.
     *
     * <p>One verb group rather than a party system beside it, because the
     * feature is "who else receives my pushes" — a property of a sync, not a
     * social structure. That is also why there is no disband and no ownership
     * transfer: the group lives exactly as long as the sync does.
     */
    private boolean sync(Player player, String[] args) {
        String sub = args.length > 1 ? args[1].toLowerCase(Locale.ROOT) : "who";
        switch (sub) {
            case "add": {
                if (args.length < 3) {
                    player.sendMessage("[RPEngine] /rpengine sync add <player>");
                    return true;
                }
                Player target = getServer().getPlayerExact(args[2]);
                if (target == null) {
                    player.sendMessage("[RPEngine] " + args[2] + " is not online.");
                    return true;
                }
                SyncGroup.Result result = group.invite(player.getName(), target.getName());
                switch (result) {
                    case OK:
                        player.sendMessage("[RPEngine] Asked " + target.getName() + ".");
                        target.sendMessage("[RPEngine] " + player.getName()
                                + " wants to share a pack with you. /rp sync accept, or deny.");
                        return true;
                    case NOT_SYNCED:
                        player.sendMessage("[RPEngine] You are not synced. /rp sync <code> first.");
                        return true;
                    case SELF:
                        player.sendMessage("[RPEngine] You already get your own pushes.");
                        return true;
                    default:
                        player.sendMessage("[RPEngine] " + target.getName() + " is already on a sync.");
                        return true;
                }
            }
            case "accept": {
                Optional<String> joined = group.accept(player.getName());
                if (joined.isEmpty()) {
                    player.sendMessage("[RPEngine] Nobody has asked you.");
                    return true;
                }
                announceMembers(joined.get());
                player.sendMessage("[RPEngine] You will get their pushes.");
                return true;
            }
            case "deny":
                player.sendMessage(group.deny(player.getName()) == SyncGroup.Result.OK
                        ? "[RPEngine] Declined."
                        : "[RPEngine] Nobody has asked you.");
                return true;
            case "remove": {
                if (args.length < 3) {
                    player.sendMessage("[RPEngine] /rpengine sync remove <player>");
                    return true;
                }
                Optional<String> code = group.remove(player.getName(), args[2]);
                if (code.isEmpty()) {
                    player.sendMessage("[RPEngine] " + args[2] + " is not on your sync.");
                    return true;
                }
                // A removal that only stopped FUTURE pushes would leave them
                // holding what they already had, which is not what remove means.
                unpush(args[2]);
                announceMembers(code.get());
                player.sendMessage("[RPEngine] Removed " + args[2] + ".");
                return true;
            }
            case "leave": {
                Optional<String> code = group.leave(player.getName());
                if (code.isEmpty()) {
                    player.sendMessage("[RPEngine] You are not on anybody's sync.");
                    return true;
                }
                unpush(player.getName());
                announceMembers(code.get());
                player.sendMessage("[RPEngine] Left.");
                return true;
            }
            case "stop": {
                List<String> were = group.stop(player.getName());
                if (were.isEmpty()) {
                    player.sendMessage("[RPEngine] You are not synced.");
                    return true;
                }
                for (String name : were) {
                    unpush(name);
                }
                group.codeOf(player.getName()).ifPresent(this::announceMembers);
                sync.forget(player.getName());
                player.sendMessage("[RPEngine] Stopped.");
                return true;
            }
            case "who": {
                Optional<String> code = group.receiving(player.getName());
                if (code.isEmpty()) {
                    player.sendMessage("[RPEngine] You are not synced. /rp sync <code> to start.");
                    return true;
                }
                player.sendMessage("[RPEngine] " + code.get() + ": "
                        + String.join(", ", group.recipients(code.get())));
                return true;
            }
            default: {
                // Anything else is a code, because that is what somebody types
                // first and asking them to write "sync code 48213097" would be
                // a word that earns nothing.
                if (!sync.link(args[1], player.getName())) {
                    player.sendMessage("[RPEngine] Could not reach studio. Check sync.url in config.yml.");
                    return true;
                }
                group.claim(args[1], player.getName());
                announceMembers(args[1]);
                player.sendMessage("[RPEngine] Synced " + args[1]
                        + ". Push from studio and it lands here. /rp sync add <player> to share it.");
                return true;
            }
        }
    }

    /**
     * Puts a pushed pack on one player.
     *
     * <p>Stacked ON TOP of whatever the server's own content gave THEM — their
     * bundle, not the claimer's, since somebody sharing a sync may be in a
     * different world with different content — so a pack under test is tried
     * against the server it will actually run on.
     */
    private void pushTo(Player player, BuiltPack pack) {
        List<BuiltPack> stack = new ArrayList<>(desiredFor(player));
        stack.removeIf(held -> held.bundle().equals(StudioPush.BUNDLE));
        stack.add(pack);
        delivery.apply(player, stack);
    }

    /** Takes a pushed pack back off somebody, leaving the server's own content. */
    private void unpush(String name) {
        Player player = getServer().getPlayerExact(name);
        if (player != null) {
            delivery.apply(player, desiredFor(player));
        }
    }

    /** Tells studio the roster, which it wants whole on every change. */
    private void announceMembers(String code) {
        List<String> entries = new ArrayList<>();
        for (String name : group.recipients(code)) {
            Player player = getServer().getPlayerExact(name);
            if (player != null) {
                entries.add(player.getUniqueId().toString().replace("-", "")
                        + ":" + player.getName() + ":java");
            }
        }
        sync.members(code, entries);
    }

    /** A give-command studio asked for, run as the console against that player. */
    private void onStudioGive(String code, String command) {
        String claimant = sync.claimant(code);
        if (claimant == null) {
            sync.giveFailed(code, "unknown-code");
            return;
        }
        getServer().getScheduler().runTask(this, () -> {
            Player player = getServer().getPlayerExact(claimant);
            if (player == null) {
                sync.giveFailed(code, "player-offline");
                return;
            }
            try {
                // @p in the command resolves against the player's own position
                // rather than the console's, which is nowhere.
                String resolved = command.startsWith("/") ? command.substring(1) : command;
                getServer().dispatchCommand(getServer().getConsoleSender(),
                        "execute at " + player.getName() + " run " + resolved);
                sync.given(code);
            } catch (RuntimeException e) {
                getLogger().warning("Studio give failed: " + e.getMessage());
                sync.giveFailed(code, "exception");
            }
        });
    }

    private void report(CommandSender to, String stage, List<Diagnostic> diagnostics) {
        for (Diagnostic diagnostic : diagnostics) {
            // The logger adds its own [RPEngine], so this one does not.
            String line = diagnostic.severity().name().toLowerCase(Locale.ROOT)
                    + " in " + stage + ": " + diagnostic;
            if (diagnostic.severity() == Diagnostic.Severity.ERROR) {
                getLogger().warning(line);
            } else {
                getLogger().info(line);
            }
            if (!(to instanceof org.bukkit.command.ConsoleCommandSender)) {
                to.sendMessage("[RPEngine] " + line);
            }
        }
    }

    /** "1 item", "2 items". Cheap, and its absence is the sort of thing that reads as unfinished. */
    private static String plural(int count, String noun) {
        return count + " " + noun + (count == 1 ? "" : "s");
    }

    /**
     * Which bundles a player should be holding.
     *
     * <p>One bundle, from the config, and that is the whole policy for now.
     * Per-world and per-permission selection is a server's decision rather
     * than ours, so it arrives as an API rather than as a guess.
     */
    private List<BuiltPack> desiredFor(Player player) {
        if (defaultBundle.isEmpty()) {
            return List.of();
        }
        for (BuiltPack pack : built) {
            if (pack.bundle().equals(defaultBundle)) {
                return List.of(pack);
            }
        }
        return List.of();
    }

    /**
     * Why an emote was refused, in words.
     *
     * <p>The engine returns a typed reason and the host writes the sentence —
     * an engine that chose the wording would be choosing the language for every
     * server that runs it. This is that choice, made once, here.
     */
    private static String emoteRefusal(ai.resourcepack.engine.api.EmoteResult result) {
        switch (result.reason()) {
            case UNKNOWN_EMOTE:
                return "No emote by that name.";
            case NO_EMOTES:
                return "This server has no emotes yet.";
            case NO_RIGS_IN_PACK:
                return "The pack has no emote rigs in it.";
            case NO_RIG_FOR_PLAYER:
                return "There is no rig for you in this pack.";
            case ALREADY_EMOTING:
                return "You are already emoting.";
            case NOT_ON_GROUND:
                return "You need to be on the ground.";
            case IN_WATER:
                return "Not in water.";
            case FLYING:
                return "Not while flying.";
            case GLIDING:
                return "Not while gliding.";
            case RIDING:
                return "Not while riding.";
            case IN_SPECTATOR:
                return "Not in spectator.";
            case NO_ROOM:
                return "Not enough room here.";
            case IN_BLOCK:
                return "Not inside a block.";
            case SOLO_EMOTE:
                return "That emote needs other players.";
            case COOLDOWN:
                return "Give it a moment.";
            case CANCELLED:
                return "Something stopped that.";
            default:
                return "Cannot do that here.";
        }
    }

    /** A radius a human typed, kept sane. Scanning a whole world is not a command. */
    private static double parseRadius(String text) {
        try {
            return Math.max(1, Math.min(128, Double.parseDouble(text.trim())));
        } catch (NumberFormatException e) {
            return 16;
        }
    }

    /** An amount a human typed. Anything unparseable is one, never a crash. */
    private static int parseAmount(String text) {
        try {
            return Math.max(1, Math.min(99, Integer.parseInt(text.trim())));
        } catch (NumberFormatException e) {
            return 1;
        }
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent event) {
        delivery.apply(event.getPlayer(), desiredFor(event.getPlayer()));
    }

    @EventHandler
    public void onQuit(PlayerQuitEvent event) {
        overlays.clear(event.getPlayer());
        // A client drops its packs on disconnect, so believing otherwise would
        // mean sending nothing to somebody who has nothing.
        sessions.forget(event.getPlayer().getUniqueId());
        // Studio stops offering to push to somebody who is not here.
        if (sync != null) {
            // If they owned a sync it ends and everybody on it loses the pack,
            // because nobody inherits one. That is the whole reason this is a
            // sync rather than a party.
            for (String name : group.forget(event.getPlayer().getName())) {
                unpush(name);
            }
            sync.forget(event.getPlayer().getName());
        }
    }

    /**
     * Every subcommand, and what each one's first argument can be.
     *
     * <p>One list rather than a switch per arity: the subcommands themselves
     * complete from its keys, so a subcommand cannot be added without also
     * being discoverable. See {@link Completions} for why that is a rule.
     */
    /**
     * What each subcommand needs.
     *
     * <p>Per subcommand rather than one node on the command, because on a real
     * server the person testing a pack is not necessarily the person who may
     * purge every model in a hundred-block radius. `rpengine.admin` is a parent
     * of the other two, so one grant still covers an owner.
     */
    private static final java.util.Map<String, String> PERMISSIONS = java.util.Map.ofEntries(
            java.util.Map.entry("reload", "rpengine.admin"),
            java.util.Map.entry("info", "rpengine.admin"),
            java.util.Map.entry("bundles", "rpengine.admin"),
            java.util.Map.entry("items", "rpengine.admin"),
            java.util.Map.entry("models", "rpengine.admin"),
            java.util.Map.entry("purge", "rpengine.admin"),
            java.util.Map.entry("recipes", "rpengine.admin"),
            java.util.Map.entry("icons", "rpengine.admin"),
            java.util.Map.entry("sounds", "rpengine.admin"),
            java.util.Map.entry("screens", "rpengine.admin"),
            java.util.Map.entry("give", "rpengine.give"),
            java.util.Map.entry("sound", "rpengine.give"),
            java.util.Map.entry("say", "rpengine.give"),
            java.util.Map.entry("screen", "rpengine.give"),
            java.util.Map.entry("hud", "rpengine.give"),
            java.util.Map.entry("push", "rpengine.give"),
            java.util.Map.entry("emotes", "rpengine.admin"),
            java.util.Map.entry("emote", "rpengine.give"),
            java.util.Map.entry("sync", "rpengine.sync"));

    private static final List<String> SUBCOMMANDS = List.of(
            "reload", "info", "bundles", "items", "give", "models", "purge",
            "sounds", "sound", "icons", "say", "screens", "screen", "hud", "recipes", "emote", "emotes", "sync", "push");

    /** Whether {@code sender} may run {@code sub}. Unknown subcommands need nothing. */
    private static boolean allowed(CommandSender sender, String sub) {
        String node = PERMISSIONS.get(sub);
        return node == null || sender.hasPermission(node);
    }

    @Override
    public List<String> onTabComplete(CommandSender sender, Command command, String alias, String[] args) {
        if (args.length <= 1) {
            // Only what they can actually run. Completing a command that then
            // refuses is worse than not completing it.
            List<String> theirs = new ArrayList<>();
            for (String sub : SUBCOMMANDS) {
                if (allowed(sender, sub)) {
                    theirs.add(sub);
                }
            }
            return Completions.matching(args.length == 0 ? "" : args[0], theirs);
        }
        if (!allowed(sender, args[0].toLowerCase(Locale.ROOT))) {
            return List.of();
        }
        String sub = args[0].toLowerCase(Locale.ROOT);
        if (args.length == 2) {
            switch (sub) {
                case "give":
                    return Completions.matchingIds(args[1], items.ids());
                case "sound":
                    return Completions.matchingIds(args[1], sounds.ids());
                case "screen":
                    return Completions.matchingIds(args[1], overlays.screenIds());
                case "hud": {
                    List<String> options = new ArrayList<>(
                            Completions.matchingIds(args[1], overlays.hudIds()));
                    options.addAll(Completions.matching(args[1], "clear"));
                    return options;
                }
                case "emote": {
                    List<String> names = new ArrayList<>(emotes.ids());
                    names.add("stop");
                    return Completions.matching(args[1], names);
                }
                case "sync":
                    // A code cannot be completed — it comes off a web page —
                    // so the words are offered and the code is simply typed.
                    return Completions.matching(args[1],
                            "add", "accept", "deny", "remove", "leave", "who", "stop");
                case "models":
                case "purge":
                    // The radii somebody actually wants, rather than nothing at
                    // all because the argument is a number.
                    return Completions.matching(args[1], "8", "16", "32", "64", "128");
                case "say":
                    // Every icon as a ready-made placeholder, because the
                    // colons are the part people get wrong.
                    return Completions.matchingIds(args[1], icons.ids()).stream()
                            .map(id -> ":" + id + ":").toList();
                default:
                    return List.of();
            }
        }
        if (args.length == 3 && sub.equals("give")) {
            return Completions.matching(args[2], "1", "8", "16", "64");
        }
        if (args.length == 3 && sub.equals("sync")) {
            String action = args[1].toLowerCase(Locale.ROOT);
            if (action.equals("add")) {
                // Only people who could actually accept: somebody already on a
                // sync cannot be added to a second one, so offering them is
                // offering a command that will refuse.
                List<String> free = new ArrayList<>();
                for (Player online : getServer().getOnlinePlayers()) {
                    if (group.receiving(online.getName()).isEmpty()) {
                        free.add(online.getName());
                    }
                }
                return Completions.matching(args[2], free);
            }
            if (action.equals("remove")) {
                return Completions.matching(args[2],
                        group.codeOf(sender.getName()).map(group::recipients).orElse(List.of()));
            }
        }
        return List.of();
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        String sub = args.length == 0 ? "info" : args[0].toLowerCase(Locale.ROOT);
        if (!allowed(sender, sub)) {
            sender.sendMessage("[RPEngine] You need " + PERMISSIONS.get(sub) + " for that.");
            return true;
        }
        switch (sub) {
            case "reload":
                // config.yml too. Reloading the content but not the settings
                // is the sort of half-reload that has somebody restarting the
                // server anyway and wondering why the command exists.
                reloadConfig();
                defaultBundle = getConfig().getString("default-bundle", "");
                rebuild(sender);
                return true;
            case "bundles":
                if (built.isEmpty()) {
                    sender.sendMessage("[RPEngine] No bundles built.");
                }
                for (BuiltPack pack : built) {
                    sender.sendMessage("[RPEngine] " + pack.bundle() + "  " + pack.entries() + " files, "
                            + pack.size() + " bytes, " + pack.sha1().substring(0, 8)
                            + "  " + host.url(pack.bundle()).orElse("not served"));
                }
                return true;
            case "give": {
                if (args.length < 2) {
                    sender.sendMessage("[RPEngine] /rpengine give <id> [amount]");
                    return true;
                }
                if (!(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] Only a player can be given an item.");
                    return true;
                }
                int amount = args.length > 2 ? parseAmount(args[2]) : 1;
                Optional<ItemStack> stack = ContentId.parse(args[1]).flatMap(id -> items.create(id, amount));
                if (stack.isEmpty()) {
                    sender.sendMessage("[RPEngine] No item called " + args[1] + ".");
                    return true;
                }
                ((Player) sender).getInventory().addItem(stack.get());
                sender.sendMessage("[RPEngine] Gave " + amount + " " + args[1] + ".");
                return true;
            }
            case "items":
                if (items.ids().isEmpty()) {
                    sender.sendMessage("[RPEngine] No items loaded.");
                }
                for (ContentId id : items.ids()) {
                    ItemInfo info = items.info(id).orElseThrow();
                    sender.sendMessage("[RPEngine] " + id + "  " + info.material()
                            + (info.model().isPresent() ? "  model " + info.model().get() : ""));
                }
                return true;
            case "models": {
                if (!(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] Only a player can look around them.");
                    return true;
                }
                Player looking = (Player) sender;
                double radius = args.length > 1 ? parseRadius(args[1]) : 16;
                java.util.List<org.bukkit.entity.Interaction> found =
                        placements.near(looking.getLocation(), radius);
                sender.sendMessage("[RPEngine] " + plural(found.size(), "model")
                        + " within " + (int) radius + " blocks.");
                for (org.bukkit.entity.Interaction hitbox : found) {
                    org.bukkit.Location at = hitbox.getLocation();
                    sender.sendMessage("[RPEngine] " + placements.idOf(hitbox).map(Object::toString).orElse("?")
                            + "  " + at.getBlockX() + " " + at.getBlockY() + " " + at.getBlockZ()
                            + (placements.isOrphan(hitbox) ? "  (orphan)" : ""));
                }
                return true;
            }
            case "purge": {
                if (!(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] Only a player can purge around them.");
                    return true;
                }
                Player around = (Player) sender;
                double radius = args.length > 1 ? parseRadius(args[1]) : 16;
                int removed = 0;
                for (org.bukkit.entity.Interaction hitbox : placements.near(around.getLocation(), radius)) {
                    // Orphans only. Purging models a pack still defines would
                    // be a demolition command wearing a cleanup command's name.
                    if (!placements.isOrphan(hitbox)) {
                        continue;
                    }
                    placements.idOf(hitbox).ifPresent(id -> placements.remove(hitbox, id, around, false));
                    removed++;
                }
                sender.sendMessage("[RPEngine] Removed " + plural(removed, "orphan")
                        + " within " + (int) radius + " blocks. Models a pack still defines were left alone.");
                return true;
            }
            case "sound": {
                if (args.length < 2) {
                    sender.sendMessage("[RPEngine] /rpengine sound <id>");
                    return true;
                }
                if (!(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] Only a player can be played a sound.");
                    return true;
                }
                boolean played = ContentId.parse(args[1])
                        .map(id -> sounds.play((Player) sender, id)).orElse(Boolean.FALSE);
                sender.sendMessage(played
                        ? "[RPEngine] Played " + args[1] + "."
                        : "[RPEngine] No sound called " + args[1] + ".");
                return true;
            }
            case "icons":
                if (icons.ids().isEmpty()) {
                    sender.sendMessage("[RPEngine] No icons loaded.");
                }
                for (ContentId id : icons.ids()) {
                    sender.sendMessage("[RPEngine] " + id + "  "
                            + icons.character(id).orElse("?") + "  :" + id + ":");
                }
                return true;
            case "say": {
                // Proof the placeholder works in ordinary text, which is the
                // whole point of putting the glyphs in the default font.
                if (args.length < 2) {
                    sender.sendMessage("[RPEngine] /rpengine say <text with :namespace:id: in it>");
                    return true;
                }
                sender.sendMessage(icons.format(String.join(" ",
                        java.util.Arrays.copyOfRange(args, 1, args.length))));
                return true;
            }
            case "screen": {
                if (args.length < 2 || !(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] /rpengine screen <id>, as a player.");
                    return true;
                }
                boolean opened = ContentId.parse(args[1])
                        .flatMap(id -> overlays.open((Player) sender, id)).isPresent();
                if (!opened) {
                    sender.sendMessage("[RPEngine] No screen called " + args[1] + ".");
                }
                return true;
            }
            case "hud": {
                if (args.length < 2 || !(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] /rpengine hud <id|clear>, as a player.");
                    return true;
                }
                if (args[1].equalsIgnoreCase("clear")) {
                    overlays.clear((Player) sender);
                    sender.sendMessage("[RPEngine] Cleared.");
                    return true;
                }
                boolean drawn = ContentId.parse(args[1])
                        .map(id -> overlays.draw((Player) sender, id)).orElse(Boolean.FALSE);
                if (!drawn) {
                    sender.sendMessage("[RPEngine] No HUD called " + args[1] + ".");
                }
                return true;
            }
            case "screens":
                for (ContentId id : overlays.screenIds()) {
                    sender.sendMessage("[RPEngine] " + id + "  "
                            + overlays.screen(id).map(o -> o.container()).orElse("?"));
                }
                for (ContentId id : overlays.hudIds()) {
                    sender.sendMessage("[RPEngine] " + id + "  "
                            + overlays.hud(id).map(o -> o.slot().name().toLowerCase(Locale.ROOT)).orElse("?"));
                }
                if (overlays.screenIds().isEmpty() && overlays.hudIds().isEmpty()) {
                    sender.sendMessage("[RPEngine] No screens or HUDs loaded.");
                }
                return true;
            case "sync": {
                if (!(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] /rpengine sync, as a player.");
                    return true;
                }
                return sync((Player) sender, args);
            }
            case "emote": {
                if (!(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] /rpengine emote <name|stop>, as a player.");
                    return true;
                }
                Player player = (Player) sender;
                if (args.length < 2 || args[1].equalsIgnoreCase("stop")) {
                    emotes.stop(player, false,
                            ai.resourcepack.engine.api.event.EmoteEndEvent.Cause.STOPPED);
                    sender.sendMessage("[RPEngine] Stopped.");
                    return true;
                }
                // The director takes the whole argument list: an emote with a
                // cast names a player per slot, and parsing that here would be
                // a second copy of a rule it already owns.
                ai.resourcepack.engine.api.EmoteResult result = emotes.perform(player,
                        List.of(java.util.Arrays.copyOfRange(args, 1, args.length)));
                if (!result.started()) {
                    sender.sendMessage("[RPEngine] " + emoteRefusal(result));
                }
                return true;
            }
            case "emotes":
                if (emotes.ids().isEmpty()) {
                    sender.sendMessage("[RPEngine] No emotes. They arrive with a studio push.");
                }
                for (String id : emotes.ids()) {
                    sender.sendMessage("[RPEngine] " + id);
                }
                return true;
            case "recipes":
                if (recipes.size() == 0) {
                    sender.sendMessage("[RPEngine] No recipes registered.");
                }
                for (ContentId id : recipeIds) {
                    sender.sendMessage("[RPEngine] " + id);
                }
                return true;
            case "sounds":
                if (sounds.ids().isEmpty()) {
                    sender.sendMessage("[RPEngine] No sounds loaded.");
                }
                for (ContentId id : sounds.ids()) {
                    sender.sendMessage("[RPEngine] " + id + "  "
                            + sounds.info(id).map(s -> s.category()).orElse("?"));
                }
                return true;
            case "push":
                if (!(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] Only a player can be pushed a pack.");
                    return true;
                }
                Player player = (Player) sender;
                sessions.forget(player.getUniqueId());
                sender.sendMessage("[RPEngine] " + (delivery.apply(player, desiredFor(player))
                        ? "Sent." : "Nothing to send."));
                return true;
            default:
                sender.sendMessage("[RPEngine] " + plural(registry.ids().size(), "id") + " across "
                        + plural(registry.namespaces().size(), "namespace") + ", "
                        + plural(built.size(), "bundle") + ".");
                List<String> kinds = new ArrayList<>();
                for (ContentKind kind : ContentKind.values()) {
                    int count = registry.ids(kind).size();
                    if (count > 0) {
                        kinds.add(plural(count, kind.name().toLowerCase(Locale.ROOT)));
                    }
                }
                sender.sendMessage("[RPEngine] " + (kinds.isEmpty() ? "nothing loaded" : String.join(", ", kinds)));
                sender.sendMessage("[RPEngine] /rpengine reload | bundles | items | give <id> [n]");
                sender.sendMessage("[RPEngine] /rpengine models [radius] | purge [radius] | push");
                sender.sendMessage("[RPEngine] /rpengine sounds | sound <id> | icons | say <text>");
                sender.sendMessage("[RPEngine] /rpengine recipes | emotes | emote <name|stop>");
                sender.sendMessage("[RPEngine] /rpengine sync <code|add|accept|deny|remove|leave|who|stop>");
                sender.sendMessage("[RPEngine] /rpengine screens | screen <id> | hud <id|clear>");
                return true;
        }
    }
}
