package ai.resourcepack.engine;

import ai.resourcepack.engine.api.BuildReport;
import ai.resourcepack.engine.api.BuiltPack;
import ai.resourcepack.engine.api.ContentKind;
import ai.resourcepack.engine.api.ContentRegistry;
import ai.resourcepack.engine.api.ContentSource;
import ai.resourcepack.engine.api.Diagnostic;
import ai.resourcepack.engine.api.LoadReport;
import ai.resourcepack.engine.api.ContentId;
import ai.resourcepack.engine.api.ItemInfo;
import ai.resourcepack.engine.api.Items;
import ai.resourcepack.engine.core.content.ContentFolderLoader;
import ai.resourcepack.engine.core.item.ItemAssets;
import ai.resourcepack.engine.core.item.ItemDefinitions;
import ai.resourcepack.engine.core.item.ItemsImpl;
import ai.resourcepack.engine.core.furniture.FurnitureDefinitions;
import ai.resourcepack.engine.core.furniture.FurnitureListener;
import ai.resourcepack.engine.core.pack.PackBuilder;
import ai.resourcepack.engine.core.registry.ContentRegistryImpl;
import ai.resourcepack.engine.core.serve.BundleSessions;
import ai.resourcepack.engine.core.serve.PackDelivery;
import ai.resourcepack.engine.core.serve.PackHost;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;

/**
 * The plugin: loads the content folder, builds a pack per bundle, serves them,
 * and hands players the bundle they should be holding.
 *
 * <p>Thin on purpose. Everything it does is assembled from pieces that work
 * without a server, so this class is wiring and console output rather than
 * logic. If something here starts making decisions, that is the signal it
 * belongs one layer down where it can be tested.
 *
 * <p><strong>The plugin name is load-bearing and cannot change.</strong>
 * Persistent-data keys are namespaced by it, so a rename would orphan
 * everything placed in every world by every earlier version.
 */
public final class RPEnginePlugin extends JavaPlugin implements Listener {

    /** So the output folder can answer "is this mine?" without anybody asking. */
    private static final String OUTPUT_README = """
            Everything in this folder is generated by RP Engine.

            Your content goes in ../content/, one folder per pack. This folder holds
            the resource packs built from it, one zip per bundle. Editing a zip here
            does nothing: the next reload overwrites it.

            Safe to delete. It is rebuilt on the next start.
            """;

    private final ContentRegistryImpl registry = new ContentRegistryImpl();
    private final BundleSessions sessions = new BundleSessions();
    private ItemsImpl items;
    private FurnitureListener furniture;

    private PackHost host;
    private PackDelivery delivery;
    private List<BuiltPack> built = List.of();
    private String defaultBundle = "";

    @Override
    public void onEnable() {
        saveDefaultConfig();
        items = new ItemsImpl(this);
        furniture = new FurnitureListener(this, items);
        getServer().getPluginManager().registerEvents(this, this);
        getServer().getPluginManager().registerEvents(furniture, this);
        startHost();
        rebuild(getServer().getConsoleSender());
    }

    @Override
    public void onDisable() {
        if (host != null) {
            host.stop();
        }
    }

    /** What this server holds. The supported way in for another plugin. */
    public ContentRegistry registry() {
        return registry;
    }

    /** The custom items this server holds. */
    public Items items() {
        return items;
    }

    private void startHost() {
        defaultBundle = getConfig().getString("default-bundle", "");
        String address = getConfig().getString("host.public-address", "http://127.0.0.1:8181");
        host = new PackHost(address);
        delivery = new PackDelivery(sessions, host,
                getConfig().getString("prompt.message", ""),
                getConfig().getBoolean("prompt.force", false));

        if (!getConfig().getBoolean("host.enabled", true)) {
            getLogger().info("Pack hosting is off. Packs are built but not served.");
            return;
        }
        try {
            int port = host.start(getConfig().getInt("host.port", 8181));
            getLogger().info("Serving packs on port " + port + " as " + address);
        } catch (IOException e) {
            getLogger().warning("Could not listen on port " + getConfig().getInt("host.port", 8181)
                    + ": " + e.getMessage() + ". Packs are built but not served.");
        }
    }

    /**
     * Reads the content folder, builds every bundle, and re-serves them.
     *
     * <p>Everything is rebuilt rather than diffed. A namespace is replaced
     * whole or not at all, and the same reasoning applies here: a partial
     * rebuild is how the registry ends up disagreeing with the zip somebody is
     * holding.
     */
    private void rebuild(CommandSender to) {
        // content/ is yours and output/ is ours. The names are doing real work
        // here: a folder called packs/ reads as "put your packs in me", which is
        // the one mistake a new user is most likely to make on day one.
        Path content = getDataFolder().toPath().resolve("content");
        Path output = getDataFolder().toPath().resolve("output");
        try {
            Files.createDirectories(content);
            Files.createDirectories(output);
            Files.writeString(output.resolve("README.txt"), OUTPUT_README);
        } catch (IOException e) {
            to.sendMessage("[RPEngine] Could not prepare " + getDataFolder() + ": " + e.getMessage());
            return;
        }

        // Everything goes, then the folder is read again. See clear().
        registry.clear();

        LoadReport loaded = new ContentFolderLoader(registry).load(content, ContentSource.AUTHORED);
        report(to, "content", loaded.diagnostics());

        ItemDefinitions.Result parsedItems = ItemDefinitions.parse(loaded);
        report(to, "items", parsedItems.diagnostics());
        // Needs a running server, so it lives out here rather than in parse().
        report(to, "items", ItemDefinitions.checkGivable(parsedItems));
        items.replace(parsedItems.items());

        FurnitureDefinitions.Result parsedFurniture =
                FurnitureDefinitions.parse(loaded, parsedItems.items());
        report(to, "furniture", parsedFurniture.diagnostics());
        furniture.replace(parsedFurniture.furniture());

        BuildReport builtReport = new PackBuilder(
                getConfig().getInt("pack.format", PackBuilder.PACK_FORMAT),
                getConfig().getString("pack.description", "RP Engine"))
                .with(new ItemAssets())
                .build(content, output, loaded);
        report(to, "build", builtReport.diagnostics());

        built = builtReport.packs();
        for (BuiltPack pack : built) {
            host.register(pack);
        }

        to.sendMessage("[RPEngine] " + plural(loaded.packs().size(), "pack") + ", "
                + plural(loaded.definitions().size(), "definition") + ", "
                + plural(built.size(), "bundle") + " built.");

        // Everybody online is holding a pack that may no longer exist, so they
        // are re-sent before they notice. Nothing is sent to a player whose
        // stack is already right.
        for (Player player : getServer().getOnlinePlayers()) {
            delivery.apply(player, desiredFor(player));
        }
    }

    private void report(CommandSender to, String stage, List<Diagnostic> diagnostics) {
        for (Diagnostic diagnostic : diagnostics) {
            // The logger adds its own [RPEngine], so this one does not.
            String line = diagnostic.severity().name().toLowerCase(Locale.ROOT)
                    + " in " + stage + ": " + diagnostic;
            if (diagnostic.severity() == Diagnostic.Severity.ERROR) {
                getLogger().warning(line);
            } else {
                getLogger().info(line);
            }
            if (!(to instanceof org.bukkit.command.ConsoleCommandSender)) {
                to.sendMessage("[RPEngine] " + line);
            }
        }
    }

    /** "1 item", "2 items". Cheap, and its absence is the sort of thing that reads as unfinished. */
    private static String plural(int count, String noun) {
        return count + " " + noun + (count == 1 ? "" : "s");
    }

    /**
     * Which bundles a player should be holding.
     *
     * <p>One bundle, from the config, and that is the whole policy for now.
     * Per-world and per-permission selection is a server's decision rather
     * than ours, so it arrives as an API rather than as a guess.
     */
    private List<BuiltPack> desiredFor(Player player) {
        if (defaultBundle.isEmpty()) {
            return List.of();
        }
        for (BuiltPack pack : built) {
            if (pack.bundle().equals(defaultBundle)) {
                return List.of(pack);
            }
        }
        return List.of();
    }

    /** An amount a human typed. Anything unparseable is one, never a crash. */
    private static int parseAmount(String text) {
        try {
            return Math.max(1, Math.min(99, Integer.parseInt(text.trim())));
        } catch (NumberFormatException e) {
            return 1;
        }
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent event) {
        delivery.apply(event.getPlayer(), desiredFor(event.getPlayer()));
    }

    @EventHandler
    public void onQuit(PlayerQuitEvent event) {
        // A client drops its packs on disconnect, so believing otherwise would
        // mean sending nothing to somebody who has nothing.
        sessions.forget(event.getPlayer().getUniqueId());
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        String sub = args.length == 0 ? "info" : args[0].toLowerCase(Locale.ROOT);
        switch (sub) {
            case "reload":
                // config.yml too. Reloading the content but not the settings
                // is the sort of half-reload that has somebody restarting the
                // server anyway and wondering why the command exists.
                reloadConfig();
                defaultBundle = getConfig().getString("default-bundle", "");
                rebuild(sender);
                return true;
            case "bundles":
                if (built.isEmpty()) {
                    sender.sendMessage("[RPEngine] No bundles built.");
                }
                for (BuiltPack pack : built) {
                    sender.sendMessage("[RPEngine] " + pack.bundle() + "  " + pack.entries() + " files, "
                            + pack.size() + " bytes, " + pack.sha1().substring(0, 8)
                            + "  " + host.url(pack.bundle()).orElse("not served"));
                }
                return true;
            case "give": {
                if (args.length < 2) {
                    sender.sendMessage("[RPEngine] /rpengine give <id> [amount]");
                    return true;
                }
                if (!(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] Only a player can be given an item.");
                    return true;
                }
                int amount = args.length > 2 ? parseAmount(args[2]) : 1;
                Optional<ItemStack> stack = ContentId.parse(args[1]).flatMap(id -> items.create(id, amount));
                if (stack.isEmpty()) {
                    sender.sendMessage("[RPEngine] No item called " + args[1] + ".");
                    return true;
                }
                ((Player) sender).getInventory().addItem(stack.get());
                sender.sendMessage("[RPEngine] Gave " + amount + " " + args[1] + ".");
                return true;
            }
            case "items":
                if (items.ids().isEmpty()) {
                    sender.sendMessage("[RPEngine] No items loaded.");
                }
                for (ContentId id : items.ids()) {
                    ItemInfo info = items.info(id).orElseThrow();
                    sender.sendMessage("[RPEngine] " + id + "  " + info.material()
                            + (info.model().isPresent() ? "  model " + info.model().get() : ""));
                }
                return true;
            case "push":
                if (!(sender instanceof Player)) {
                    sender.sendMessage("[RPEngine] Only a player can be pushed a pack.");
                    return true;
                }
                Player player = (Player) sender;
                sessions.forget(player.getUniqueId());
                sender.sendMessage("[RPEngine] " + (delivery.apply(player, desiredFor(player))
                        ? "Sent." : "Nothing to send."));
                return true;
            default:
                sender.sendMessage("[RPEngine] " + plural(registry.ids().size(), "id") + " across "
                        + plural(registry.namespaces().size(), "namespace") + ", "
                        + plural(built.size(), "bundle") + ".");
                List<String> kinds = new ArrayList<>();
                for (ContentKind kind : ContentKind.values()) {
                    int count = registry.ids(kind).size();
                    if (count > 0) {
                        kinds.add(plural(count, kind.name().toLowerCase(Locale.ROOT)));
                    }
                }
                sender.sendMessage("[RPEngine] " + (kinds.isEmpty() ? "nothing loaded" : String.join(", ", kinds)));
                sender.sendMessage("[RPEngine] /rpengine reload | bundles | items | give <id> [n] | push");
                return true;
        }
    }
}
